### ISSUE TITLE
Fix layout for Object page

### ISSUE THREAD

**Issue by mgboydcom** [travelgateX/Issue-tracker#10]
**Describe the bug**
Layout issues

**To Reproduce**
See [https://docs.travelgatex.com/travelgatex/reference/objects/]

**Expected behavior**
Cleaner layout
Mark to submit pull request by mid June

**Comment by jjdiezm** [comment]
We are working on a style [guide](https://docs.travelgatex.com/community/style-guide) to standardize how pages must be filled. Objects are clear now.
