### ISSUE TITLE
Non dummy responses for anonymous users

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#11]
[Public documentation](https://docs.travelgatex.com/hotelx/quickstart/) test API Key is configured to use a Dummy supplier.

Would be recommended to have an API key configured to use a Test Supplier. This will help to test real workflows, i.e. error codes

**Comment by abasalo** [comment]
The new workflow documented in our [Public documentation](https://docs.travelgatex.com/hotelx/quickstart/), has been changed to attack our real test provider: 
`settings: {client: "Demo_Client", testMode: true, context: "HOTELTEST"}) `

The client could change the criteria and obtain different responses in real time.
