### ISSUE TITLE
Remove Github Link from auto-generated "reference" pages

### ISSUE THREAD

**Issue by pedrobc** [travelgateX/Issue-tracker#14]
Pages like https://docs.travelgatex.com/travelgatex/reference/enums/bookstatustype/ get generated automatically from the GraphQL schema thus should not have a link to edit in GitHub and must be identified as such.

**Comment by arquio** [comment]
Solved in https://github.com/travelgateX/documentation-site/pull/216

thanks @SrNemuri !!
