### ISSUE TITLE
Deprecate/Sustitute KO by NOK

### ISSUE THREAD

**Issue by arquio** [travelgateX/Issue-tracker#15]
**To Reproduce**
1. Go to https://github.com/travelgateX/graphql-schema/blob/master/hotelx/hubgra/enums/enum_BookStatusType.graphql
```graphql
# Book status
enum BookStatusType {
  # The reservation was completed with no problems
  OK
  
  # The status of the booking is KO
  KO
  
  # The reservation was completed but the product is still not available, so the reservation goes into a waiting list.
  # It is the client’s responsibility to check if the booking is OK
  ON_REQUEST
  
  # The status of the booking is cancelled
  CANCELLED
  
  # The reservation was completed but due to a supplier error or a timeout, the reservation status is unknown.
  # It is the client’s responsibility to check if the booking is OK
  UNKNOWN
}
```

**Comment by arquio** [comment]
Graphql schema updated.

**Comment by abasalo** [comment]
We will remove the status KO in next week. This status was inherited from legacy API to differentiate when the call to the provider was made. At the moment it does not make sense, with the rest of status we contemplate all the possible cases.

**Comment by rubencaballero** [comment]
Hi, this field has been marked as deprecated and this pending for delete.

Thanks
