### ISSUE TITLE
Unused fields on schema

### ISSUE THREAD

**Issue by SrNemuri** [travelgateX/Issue-tracker#17]
I have been working on the script that generates the `.md` files for for the `documentation-site` project. While I was on it, i found some fields are not used at all.

  - PriceType
  - ServiceType
  - AccessConnectUserInput
  - AccessSupplierInput
  - DefaultSettingsInput
  - IdGroupAccessInput
  - MappeaAddOrganizationInput
  - MappeaEditOrganizationInput
  - fake__Locale
  - fake__Types
  - fake__options
  - examples__JSON

And maybe there are more. I am going to look into this issue to find which fields make the script not work properly

**Comment by arquio** [comment]
Hey @pperaltaisern @bsmarcosj . Can you review this graphql objects?? can we deleted from graphql-schema?

Thanks!!!

**Comment by rubencaballero** [comment]
Hi, @SrNemuri the first six fields isn't used and you can delete it.

- PriceType
- ServiceType
- AccessConnectUserInput
- AccessSupplierInput
- DefaultSettingsInput
- IdGroupAccessInput
