### ISSUE TITLE
Update info to Query Destinations (Website-SearchbyDestinations)

### ISSUE THREAD

**Issue by dmerida** [travelgateX/Issue-tracker#18]
Update Query Destinations (important information is missing from the Query):

```
query ($criteria: HotelXDestinationListInput!, $token: String) {
  hotelX {
    destinations(criteria: $criteria, token: $token, relay: {}) {    
			token
      edges {
        node {
          error {
            code
            type
            description
          }
          destinationData {
            code
            available
            destinationLeaf
            texts {
              text
              language
            }
            closestDestinations
            parent
            type
          }
        }
      }
    }
  }
}

```

**Comment by dmerida** [comment]
https://docs.travelgatex.com/hotelx/plugins/search_by_destination/

**Comment by abasalo** [comment]
Good morning @dmerida !

We updated our documentation the complete destination query with all parameters: https://docs.travelgatex.com/hotelx/concepts/content/

And we mentioned it in the plugin "search_by_destination":  https://docs.travelgatex.com/hotelx/plugins/search_by_destination/

In the following section: ### Query get hotels & destination Get hotels & destinations

![imagen](https://user-images.githubusercontent.com/6781001/47418967-7b09f700-d77b-11e8-8f75-cab0eea13035.png)

If there is something that can be improved, do not hesitate to contact us.
