### ISSUE TITLE
DOCUMENTATION OF ERRORS

### ISSUE THREAD

**Issue by dmerida** [travelgateX/Issue-tracker#22]
In order to document currently undocumented errors returned by the API. Especially the 500. Here is my contribution with the translation to Spanish of the 502-597 errors

SPANISH TRANSLATION:

* Error 597: La conexión se ha cerrado forzosamente por el punto de acceso de destino. Normalmente resulta en una pérdida de conexión del socket remoto debido a un timeout o reinicio. Normalmente se encuentra en los módulos http y net
* Error 502: El servidor, mientras está actuando de gateway o proxy, recibe una respuesta inválida por parte de un servidor de entrada al que accedía mientras trataba de llevar a cabo una petición.

_________________

ORIGINAL TEXT:

597: A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the http and net modules.

502: The server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request.

_PD. My special thanks to all the members of TeamX who have helped me with the translation of the word "peer"!

**Comment by dmerida** [comment]
Footnote: the translation to Spanish is meant to be used in the resolution of Customer Care tickets. The original English text in the Documentation Website. However, should anyone think some extra info must be added for the sake of the client's interest, please let us know. Thanks!! :)

**Comment by abasalo** [comment]
Thank you very munch @dmerida !

We need to work hard in our documentation to be able to make connectivity easier. We are looking at how to deal the error types. Should add the explication of errors types in the same section of HotelX? 
We are thinking about making generalized errors, but we have not finished analyzing them

We will take into account all the types of errors, both general and the specific of the product. We try to always be in English sinse it's the standard language, do you think?

Thanks again!

**Comment by dmerida** [comment]
Good morning @abasalo 

Thank you for your comments!! In fact, the explanation of those errors in English was provided to me by the HubAgrr team, but it's not yet included in the website.

Currently, there is one HotelX Common Errors Sections in progress, I think that should be the place: https://docs.travelgatex.com/hotelx/faqs/common-errors/

Regarding your previous comment on the Spanish language used, the Spanish translation was thought in order to reply to our Spanish-speaking customers in our Customer Care Portal - I though it would be useful to have the corresponding Spanish translation for those errors - since we are speaking of technical vocabulary which could have some specific technical connotations that must managed carefully (they cannot sometimes be translated literally) and since those translations are supposed to be a standard reply by our team and think they should also be better supervised by the rest of our team.

Thank you!

**Comment by rubencaballero** [comment]
Hi, a first draft of the error codes has been put in the documentation by Core team ([https://docs.travelgatex.com/travelgatex/concepts/http-response-status-codes/])

Thanks.
