### ISSUE TITLE
Update hotelX examples

### ISSUE THREAD

**Issue by arquio** [travelgateX/Issue-tracker#24]
The hotelX's examples need update.

https://docs.travelgatex.com/hotelx/quickstart/#search

![screenshot from 2018-11-26 15-51-55](https://user-images.githubusercontent.com/414590/49021831-d1f85700-f193-11e8-8e06-f53b591884bf.png)

**Comment by rubencaballero** [comment]
Hi, recently we have updated example of "search" query.

https://docs.travelgatex.com/hotel-x/methods/bookingflow/search/

Thanks.
