### ISSUE TITLE
Update Schema + TravelgateX documentation website

### ISSUE THREAD

**Issue by dmerida** [travelgateX/Issue-tracker#27]
Good afternoon team,

As requested by Abel Jarillo, we need to check and update the TravelgateX documentation website and HotelX schema with the following definitions (the following information is only a sample):
```
"cursor": "NDUjaG90ZWx0ZXN0", Cursor is an ID used for the relay, we use it internally in our the website.
                       "node": {
                           "code": "NDUjaG90ZWx0ZXN0", code is the unique ID of the room in our database. It is only for our internal use.
                           "roomData": {
                               "code": "NDUjaG90ZWx0ZXN0", code is the unique ID of the room in our database. It is only for our internal use.
                               "roomCode": "45", RoomCode is the supplier room code. It is the one you should map.
                               "texts": [
```

Since I assume this might imply two different procedures (one for the website, and one for the HotelX Schema) I would need to confirm which is the protocol to request this, and/or subsequent modifications and updates similar to this one in the future.

Moreover, feel free to add or modify any aspect in the aforementioned information.

Looking forward to your feedback and thanking you in advance,

Kind regards,

Dulce M. Mérida

**Comment by arquio** [comment]
hi!
Here ( https://github.com/travelgateX/graphql-schema ) you can request shcema modifications 

Thanks
