### ISSUE TITLE
Partner Template Overview

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#28]
From a seller/buyer partner point of view current overview reporting page it's not concise, i.e. ADR it's not the most important partner KPI

I would like to visualize generic KPIs to go through a Top-Down analysis, some KPIs but not all:
- Yesterday books and trend
- Yesterday cancels  and trend
- Top buyers or sellers

After this 1st overview, we could go through other KPIs as ADR

**Comment by jroda** [comment]
We added info about bookings and cancellations trends to our partner's report (buyer/seller)
