### ISSUE TITLE
Reporting Template L2R

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#30]
L2R it's a good KPI for Hoteliers but opinable for partner's

For partner template (buyer or seller) add other important KPI as B2C, in case both KPIs can't coexist I would prefer B2C over L2R

Also, for L2R try to explain what this means, maybe an acronym resume in the last page?

**Comment by jroda** [comment]
There are available next list of KPIs:
- L2Q: Quantity of searches per quote.
- Q2B: Quantity of quotes per booking.
- B2C: Quantity of bookings per cancel.
- L2B: Quantity of searches per booking.
