### ISSUE TITLE
Report Portfolio page

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#32]
Portfolio is a great insight, but displays suppliers product overall TravelgateX customers.

It would be great if hotels can be tagged with a flag indicating if the product is for other customers or specific for partner user credentials.

So 2 different analysis can be performed:

- What product as other competitors that I do not have?
- About my own product, what is the usage?

**Comment by jroda** [comment]
At this moment we can't difference between the specific product of one client and his competitive set's product.

About the second point, we added the usage of each hotel with the portfolio info.

More info in our [doc](https://docs.travelgatex.com/insights-x/)

**Comment by Patricia-Insights** [comment]
We want to reopen this issue and give more details in Portfolio report by filtering hotels:

1) Hotels only for the specific partner  (my hotels)
2) Hotels for other customer (all hotels)

**Comment by Patricia-Insights** [comment]
We close this request at this feature requires extra development. 
It might be done under request with extra charge for the TCP.
