### ISSUE TITLE
Dataset documentation

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#33]
It's frustrated to do not have documentation about data in Data Sets.

I would like to have this information in order to figure out how I can explore the data getting the correct insights.

Dataset documentation should exist under an Insights section [here](https://docs.travelgatex.com/getting-started/)

Please, consider documenting using a [Kaggle](https://www.kaggle.com/datasets) style or some other DataSet standard way to document

**Comment by jroda** [comment]
We made a first version of documentation. It is available [here](https://docs.travelgatex.com/insights-x/)
