### ISSUE TITLE
Price Type information

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#34]
In Datasets, price information is ambiguous. Possible combinations of sellers/buyers can generate different types of price:

1. Nets
2. Commissionable with a well-known commission -> can be transformed to a net price
3.  Unknown type

All datasets containing prices should manage this information. i.e. indicating the price type or an extra column informing about the commission.

**Comment by jroda** [comment]
In our datasets now we've divided booking's info between bookings with net prices and bookings where we aren't able to know if it is a net price or contains a commission.
