### ISSUE TITLE
Information page in reports

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#35]
Add an information page for all report templates.

I would like all reports has an information/appendix page to summarize the data sources data used 

Ideally, the information page should contain:
- Quality of data used (i.e. % of hotels processed with a valid Destination) 
- Dataset metadata as storage used
- Any extra information that can not be exposed in competitive sets due to privacy terms (i.e. the number and category of hotels uses in the competitive set)

This information also must be available for Dataset consumers.

**Comment by jroda** [comment]
Each of our report contains a page with info about the size of your own dataset, volume of data analyzed and other useful info like quantity of buyers/sellers used in your benchmarking.
