### ISSUE TITLE
Ranking PKIS

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#36]
Competitive set is very useful, it will be great if we can benchmark about product performance.

**This insight is useful for partners buyers and sellers**

- Product availability:
   - How is my search availability vs my competitive set?  
   - Useful for partners sellers to be competitive in destinations/hotel-segmentation
   - Useful for partners buyers to track uncovered demand in destinations/hotel-segmentation
   - Implement as, a graph with % availability in destination vs competitive set

- Product price:
   - How is my search price vs my competitive set?
   - Useful for partners sellers to be competitive in destinations/hotel-segmentation
   - Useful for partners buyers to track uncovered demand in destinations/hotel-segmentation
   - Useful for hoteliers to track availability errors
   - Implement as, a graph with % availability in destination vs competitive set

- Product bookability:
   - How I book vs my competitive set?
   - Useful for partners sellers to be competitive in destinations/hotel-segmentation
   - Useful for partners buyers to revenue destinations/hotel-segmentation
   - Implement as, a graph with % books  in destination vs competitive set

All this KPIs must be ranked vs Clients (for buyers) and Suppliers (for sellers)

**Comment by jroda** [comment]
There is available the first version of these KPIS. 

In our [doc](https://docs.travelgatex.com/insights-x/) is shown more info about these KPIS and how work with them.
