### ISSUE TITLE
Change title name

### ISSUE THREAD

**Issue by mvermeulenX** [travelgateX/Issue-tracker#37]
In the Buyers report, the title name on pages 4, 5  and 6 (Performance) called %Error leads to confusion, since it seems that it is indicating the amount of errors related to the total amount of requests.

A better name should be "Error Analysis" or "Error distribution", so that it is clear that the percentages are related to the amount of errors, not the total amount of requests.

**Comment by jroda** [comment]
We've changed the title by "Errors distribution". It's more clear now.
