### ISSUE TITLE
Book on the example Query at HotelX docs - Booking process - Booking List

### ISSUE THREAD

**Issue by jjdiezm** [travelgateX/Issue-tracker#50]
**Describe the bug**
Example query is missing mandatory fields, when executing example returns:

``` JSON
{
  "data": {
    "hotelX": {
      "booking": {
        "bookings": null,
        "errors": [
          {
            "code": "MISSING_FIELD",
            "type": "VALIDATION_ERROR",
            "description": "client missing in settings"
          }
        ],
        "warnings": null
      }
    }
  }
}
```

**To Reproduce**
1. Go to 'https://docs.travelgatex.com/hotel-x/howtos/bookingflow/booklist/'
2. Click on 'Example Query'
3. See error

**Expected behavior**
Exepected a correct response at the example.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 75.0.3770.100 (Build oficial) (64 bits)

**Comment by jjdiezm** [comment]
Reported by Melvin as a PR at docs repository:
https://github.com/travelgateX/documentation-site/pull/551/commits/7591b19985e5721f45497d4f55c8f389179aaaa8

**Comment by jjdiezm** [comment]
Gist URL: https://gist.github.com/tgx-bot/2bee5af21dd6f2cc61eec736bb95aead

**Comment by abasalo** [comment]
The problem is in the criterian, is missing the client tag in the settings level:

```
	"settings": {
		"client": "XXX",
		"testMode": true
	}
```

It's mandatory the client or group:

![imagen](https://user-images.githubusercontent.com/6781001/61294755-d337cc00-a7d6-11e9-8395-313e4a63a2bf.png)

**Comment by rubencaballero** [comment]
Hi, example of booking is currently updated and fixed.

https://docs.travelgatex.com/hotel-x/methods/reservationmanagement/booklist/

Thanks.
