### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by rameshchanty** [travelgateX/Issue-tracker#52]
**Describe the bug**

**To Reproduce**
2. Click on 'https://docs.travelgatex.com/hotel-x/quickstart/
![error](https://user-images.githubusercontent.com/61863206/76389427-32afa100-6391-11ea-9f7f-2da1ee15b6c4.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rubencaballero** [comment]
Hi, recently we have changed the structure of the documentation and the link you indicate no longer exists, so the error is correct.

How did you get to navigate to that link?

**Comment by rameshchanty** [comment]
Hi,



I got link from slack 

Regards,   



Ramesh Chakali  |  Sr.Software Engineer 
           QuicSolv Technologies Pvt. Ltd.
Office: +91 20 48602420          Direct:           +91 9642866415         

 

_________________________________________

This e-mail communication and any attachments to it are confidential and privileged to QuicSolv Technologies Pvt. Ltd. and are strictly intended only for the personal and confidential use of the designated recipient(s) named above. If you are not the intended recipient of this message, you are hereby notified that any review, dissemination, distribution or copying of this message is strictly prohibited and may be unlawful.     







---- On Wed, 11 Mar 2020 15:03:58 +0530 Rubén Caballero Martín <notifications@github.com> wrote ----


Hi, recently we have changed the structure of the documentation and the link you indicate no longer exists, so the error is correct.

How did you get to navigate to that link?

**Comment by rubencaballero** [comment]
That link shouldn't appear anymore. Thanks
