### ISSUE TITLE
Booking query should return all possible fields

### ISSUE THREAD

**Issue by operezfuentes** [travelgateX/Issue-tracker#6]
I'm frustrated how suppliers manage BookingList and BookingDetail. Most of them implement:

BookingDetail: Usually can be filtered by booking references
BookingList: Usually can be filtered by Booking Date Ranges
I expect HotelX API facade these 2 calls into one single call as expected in Booking query.
A customer could request for all filters, and based on graphQL request fields, execute List and/or Detail when necessary.

Currently, the workaround to implement on customer side:

Use booking query using date criteria
For each book responded, use booking query using booking reference criteria

**Comment by rubencaballero** [comment]
Currently in the Booking call, all the detail of the reservation is already returned and it also has some filters implemented.
