### ISSUE TITLE
Plugin pages need edits

### ISSUE THREAD

**Issue by mgboydcom** [travelgateX/Issue-tracker#7]
**Describe the bug**
All pages of the HotelX plugin pages need edits and to have some examples of the report table formats

**To Reproduce**
Pages under [https://docs.travelgatex.com/hotelx/plugins/](https://docs.travelgatex.com/hotelx/plugins/) have not been reviewed yet.

**Expected behavior**
Mark to do initial review by mid-June and push edits in pull request.

**Additional context**
By end of June

**Comment by operezfuentes** [comment]
Plugin definitions also must impelement a common template. 
i.e.  https://docs.travelgatex.com/hotelx/plugins/search_by_destination/

Does not follow any standard

**Comment by jjdiezm** [comment]
Hub team is working on plugin definition and on defining a common template for them.

**Comment by rubencaballero** [comment]
All new plugins and each time we update one, this template is applied in which we incorporate a sample file, use cases and example of a request.
