### ISSUE TITLE
Update Playground explanation page

### ISSUE THREAD

**Issue by mgboydcom** [travelgateX/Issue-tracker#8]
**Describe the bug**
Page needs a bit more detail and some examples.

**To Reproduce**
See [https://docs.travelgatex.com/getting-started/playground/]

**Expected behavior**
- Show simple query for searching for a hotel
- Show response for query
- Set up playground to show the above
- Underneath playground embed, add suggestions for how to extend your search, eg. try adding a search for specific amenity 

Mark to edit by mid-June and submit a pull request.

**Comment by operezfuentes** [comment]
Hi @mgboydcom ,

Use of playground embedded in TravelgateX documentation has been deprecated in favour of graphiql. Lighter and clearer.
